// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izecjwqmmeintgmngyde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6ZWNqd3FtbWVpbnRnbW5neWRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MjU3NzQsImV4cCI6MjA2MDIwMTc3NH0.7QXqtwwPgfSNhapS_8noqI3OZS37C32MNUUtVMrigg4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);